name: flutter_application_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1" 
  cloud_firestore: "^0.16.0+1"
  firebase_messaging: "^8.0.0-dev.15"
  cloud_functions: "^0.9.0"
  firebase_storage: "^7.0.0"
  firebase_database: "^6.0.0"
 







  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  carousel_pro: ^1.0.0
  carousel_slider: ^3.0.0
  curved_navigation_bar: ^0.3.7
  animated_drawer: ^0.0.4
  google_sign_in: "^4.5.1"
  intro_screen_onboarding_flutter: ^0.1.5
  flutter_onboard: ^1.0.0
  nice_intro: ^0.1.4
  awesome_dialog: ^2.1.0









  #flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assest/images/doctor.png
    - assest/images/list1.png
    - assest/images/list2.png
    - assest/images/main_top.png
    - assest/images/main_bottom.png
    - assest/images/login_bottom.png
    - assest/images/wel1.png
    - assest/images/wel2.png
    - assest/images/signup_top.png
    - assest/images/log1.png
    - assest/images/log2.png
    - assest/images/log3.png
    - assest/images/med1.png
    - assest/images/med2.png
    - assest/images/wow.png
    - assest/images/med3.png
    - assest/images/log4.jpg
    - assest/images/log66.png
    - assest/images/r1.png
    - assest/images/r2.png
    - assest/images/cir1.png
    - assest/images/logo.jpg
    - assest/images/new1.png
    - assest/images/new2.png
    - assest/images/google.png
    - assest/images/facebook.png
    - assest/images/corona.jpg
    - assest/images/corona2.jfif
    - assest/images/corona3.jfif
    - assest/images/corona4.jpg
    - assest/images/corona5.jfif
    - assest/images/herbal.png
    - assest/images/natural.png
    - assest/grid/list.png
    - assest/grid/syringe.png
    - assest/grid/make.png
    - assest/grid/mask.png   
    - assest/grid/pharmacy.png
    - assest/grid/paste.png
    - assest/grid/cream.png
    - assest/grid/heart.png
    - assest/grid/drugs.png
    - assest/grid/soul2.png
    - assest/grid/logo.png
    - assest/grid/aid.png
    - assest/grid/soul.png
    - assest/images/on1.png
    - assest/images/on2.png
    - assest/images/on3.png
    - assest/images/on4.png


    












    
    








     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
